# name: fps_admin
# description: Admin app to monitor and manage orders via polling (no cloud).
# publish_to: "none"
# version: 0.1.0+1

# environment:
#   sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   dio: ^5.4.0
#   shared_preferences: ^2.2.2
#   intl: ^0.19.0
#   firebase_core: ^2.30.0
#   firebase_messaging: ^14.9.0
#   flutter_local_notifications: ^17.1.2
#   http: ^1.2.2
#   file_picker: ^8.0.3

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0
#   flutter_launcher_icons: ^0.13.1

# flutter:
#   uses-material-design: true

# # Tool configuration (root-level, same indent as `flutter:`)
# flutter_launcher_icons:
#   image_path: assets/app_icon/icon.png

#   android: true
#   ios: true
#   web:
#     generate: true
#     image_path: assets/app_icon/icon.png
#     background_color: "#FFFFFF"
#     theme_color: "#1E88E5"

#   macos:
#     generate: true
#     image_path: assets/app_icon/icon.png
#   linux:
#     generate: true
#     image_path: assets/app_icon/icon.png
#   windows:
#     generate: true
#     image_path: assets/app_icon/icon.png

#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: assets/app_icon/icon.png
#   # adaptive_icon_monochrome: assets/app_icon/icon_monochrome.png
#   min_sdk_android: 21


name: fps_admin
description: Admin app to monitor and manage orders via polling (no cloud).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.1.2
  http: ^1.2.2
  flutter_launcher_icons: ^0.13.1
  # NEW for Android-only file save & picker
  path_provider: ^2.1.4
  file_picker: ^8.0.3
  open_filex: ^4.5.0
  permission_handler: ^11.1.0
  url_launcher: ^6.3.2
  flutter_riverpod: ^3.3.1
  go_router: ^17.0.0
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/app_icon/icon.png
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/app_icon/icon.png
    background_color: "#FFFFFF"
    theme_color: "#1E88E5"
  macos:
    generate: true
    image_path: assets/app_icon/icon.png
  linux:
    generate: true
    image_path: assets/app_icon/icon.png
  windows:
    generate: true
    image_path: assets/app_icon/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon/icon.png
  min_sdk_android: 21
