import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import '../firebase_options.dart'; // generated by flutterfire configure

class PushService {
  PushService._();

  static bool _firebaseReady = false;
  static StreamSubscription<String>? _refreshSub;

  // ── Order-refresh signal ──────────────────────────────────────────────────
  static final StreamController<void> _orderRefreshCtrl =
      StreamController<void>.broadcast();

  /// Listen to this stream to know when orders should be reloaded.
  static Stream<void> get onOrderRefresh => _orderRefreshCtrl.stream;

  /// Call this whenever a push notification indicates new/changed orders.
  static void triggerRefresh() => _orderRefreshCtrl.add(null);
  // ─────────────────────────────────────────────────────────────────────────

  /// Be gentle: safe to call multiple times.
  static Future<void> ensureInitialized() async {
    if (!_firebaseReady) {
      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }
      await FirebaseMessaging.instance.setAutoInitEnabled(true);
      _firebaseReady = true;
    }
  }

  /// Android 13+ needs runtime permission; iOS always does.
  static Future<NotificationSettings> ensurePermissions() async {
    await ensureInitialized();
    final settings = await FirebaseMessaging.instance.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );
    return settings;
  }

  static Future<String?> currentToken() async {
    await ensureInitialized();
    return FirebaseMessaging.instance.getToken();
  }

  static Future<void> registerDeviceWithBackend({
    required String backendBaseUrl, // e.g. https://host/api
    required String authToken,
    required bool isAdmin,
  }) async {
    await ensureInitialized();

    final token = await currentToken();
    if (token == null || token.isEmpty) return;

    final platform = Platform.isAndroid
        ? 'android'
        : Platform.isIOS
            ? 'ios'
            : 'web';

    final base =
        backendBaseUrl.endsWith('/') ? backendBaseUrl : '$backendBaseUrl/';
    final uri = Uri.parse('${base}me/devices/');

    try {
      final resp = await http.post(
        uri,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Token $authToken',
        },
        body: jsonEncode({
          'token': token,
          'platform': platform,
          'is_admin': isAdmin,
        }),
      );
      if (resp.statusCode >= 400) {
        debugPrint('Device register failed (${resp.statusCode}): ${resp.body}');
      }
    } catch (e) {
      debugPrint('Device register error (non-blocking): $e');
    }
  }

  /// Keep backend in sync when FCM rotates the token.
  static void subscribeTokenRefresh({
    required String backendBaseUrl,
    required Future<String?> Function() getAuthToken,
    required bool isAdmin,
  }) {
    _refreshSub?.cancel();
    _refreshSub =
        FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
      final auth = await getAuthToken();
      if (auth == null || auth.isEmpty) return;
      try {
        await registerDeviceWithBackend(
          backendBaseUrl: backendBaseUrl,
          authToken: auth,
          isAdmin: isAdmin,
        );
      } catch (e) {
        debugPrint('Token refresh re-register failed: $e');
      }
    });
  }

  static Future<void> cancelTokenRefresh() async {
    await _refreshSub?.cancel();
    _refreshSub = null;
  }
}
