// // lib/services/push_service.dart
// import 'dart:io';
// import 'dart:convert';
// import 'package:http/http.dart' as http;
// import 'package:firebase_messaging/firebase_messaging.dart';

// class PushService {
//   static final FirebaseMessaging _fm = FirebaseMessaging.instance;

//   /// Ask for runtime permission when needed (Android 13+/iOS)
//   static Future<void> ensurePermissions() async {
//     if (Platform.isAndroid) {
//       // On Android 13+ POST_NOTIFICATIONS is runtime; firebase_messaging handles it via requestPermission.
//       await _fm.requestPermission();
//     } else {
//       await _fm.requestPermission(alert: true, badge: true, sound: true);
//     }
//   }

//   static Future<String?> getFcmToken() async {
//     try {
//       return await _fm.getToken();
//     } catch (_) {
//       return null;
//     }
//   }

//   /// Registers this device token with your Django backend.
//   static Future<void> registerDeviceWithBackend({
//     required String
//         backendBaseUrl, // e.g. https://fps-dayalbagh-backend.vercel.app/api
//     required String authToken, // DRF token from login
//     required bool isAdmin, // true for shopkeeper/admin app
//   }) async {
//     final token = await getFcmToken();
//     if (token == null || token.isEmpty) return;

//     final url = Uri.parse('$backendBaseUrl/me/devices/'); // /api/me/devices/
//     final resp = await http.post(
//       url,
//       headers: {
//         'Content-Type': 'application/json',
//         'Authorization': 'Token $authToken',
//       },
//       body: jsonEncode({
//         'token': token,
//         'platform': Platform.isIOS ? 'ios' : 'android',
//         'is_admin': isAdmin,
//       }),
//     );

//     // Don’t throw even if it fails; login should not be blocked.
//     // Print/logging left out intentionally.
//   }
// }

// lib/services/push_service.dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:http/http.dart' as http;

import '../firebase_options.dart'; // generated by flutterfire configure

class PushService {
  PushService._();

  static bool _firebaseReady = false;
  static StreamSubscription<String>? _refreshSub;

  /// Be gentle: safe to call multiple times.
  static Future<void> ensureInitialized() async {
    if (!_firebaseReady) {
      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }
      await FirebaseMessaging.instance.setAutoInitEnabled(true);
      _firebaseReady = true;
    }
  }

  /// Android 13+ needs runtime permission; iOS always does.
  static Future<NotificationSettings> ensurePermissions() async {
    await ensureInitialized();
    final settings = await FirebaseMessaging.instance.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );
    return settings;
  }

  static Future<String?> currentToken() async {
    await ensureInitialized();
    return FirebaseMessaging.instance.getToken();
  }

  /// Registers (or updates) this device in your Django backend.
  ///
  /// Example backend expects:
  ///   POST /api/me/devices/
  ///   body: { token, platform, is_admin }
  ///   header: Authorization: Token <DRF token>
  static Future<void> registerDeviceWithBackend({
    required String backendBaseUrl, // e.g. https://host/api
    required String authToken,
    required bool isAdmin,
  }) async {
    await ensureInitialized();

    final token = await currentToken();
    if (token == null || token.isEmpty) {
      // Nothing we can do—FCM not ready yet.
      return;
    }

    final platform = Platform.isAndroid
        ? 'android'
        : Platform.isIOS
            ? 'ios'
            : 'web';

    final uri = Uri.parse(
      backendBaseUrl.endsWith('/')
          ? '${backendBaseUrl}me/devices/'
          : '$backendBaseUrl/me/devices/',
    );

    await http.post(
      uri,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Token $authToken',
      },
      body: jsonEncode({
        'token': token,
        'platform': platform,
        'is_admin': isAdmin,
      }),
    );
    // We intentionally don’t throw on non-200; login flow shouldn’t be blocked.
  }

  /// Keep backend in sync when FCM rotates the token.
  /// Call this once after login. It cancels/replaces any previous listener.
  static void subscribeTokenRefresh({
    required String backendBaseUrl,
    required Future<String?> Function() getAuthToken,
    required bool isAdmin,
  }) {
    _refreshSub?.cancel();
    _refreshSub =
        FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
      final auth = await getAuthToken();
      if (auth == null || auth.isEmpty) return;
      try {
        await registerDeviceWithBackend(
          backendBaseUrl: backendBaseUrl,
          authToken: auth,
          isAdmin: isAdmin,
        );
      } catch (_) {
        // Silently ignore; we’ll try again on next refresh.
      }
    });
  }

  /// Optional: call on logout.
  static Future<void> cancelTokenRefresh() async {
    await _refreshSub?.cancel();
    _refreshSub = null;
  }
}
