// import 'dart:async';
// import 'dart:convert';
// import 'dart:io';

// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'package:http/http.dart' as http;

// import '../firebase_options.dart'; // generated by flutterfire configure

// class PushService {
//   PushService._();

//   static bool _firebaseReady = false;
//   static StreamSubscription<String>? _refreshSub;

//   /// Be gentle: safe to call multiple times.
//   static Future<void> ensureInitialized() async {
//     if (!_firebaseReady) {
//       if (Firebase.apps.isEmpty) {
//         await Firebase.initializeApp(
//           options: DefaultFirebaseOptions.currentPlatform,
//         );
//       }
//       await FirebaseMessaging.instance.setAutoInitEnabled(true);
//       _firebaseReady = true;
//     }
//   }

//   /// Android 13+ needs runtime permission; iOS always does.
//   static Future<NotificationSettings> ensurePermissions() async {
//     await ensureInitialized();
//     final settings = await FirebaseMessaging.instance.requestPermission(
//       alert: true,
//       announcement: false,
//       badge: true,
//       carPlay: false,
//       criticalAlert: false,
//       provisional: false,
//       sound: true,
//     );
//     return settings;
//   }

//   static Future<String?> currentToken() async {
//     await ensureInitialized();
//     return FirebaseMessaging.instance.getToken();
//   }

//   /// Registers (or updates) this device in your Django backend.
//   ///
//   /// Example backend expects:
//   ///   POST /api/me/devices/
//   ///   body: { token, platform, is_admin }
//   ///   header: Authorization: Token <DRF token>
//   static Future<void> registerDeviceWithBackend({
//     required String backendBaseUrl, // e.g. https://host/api
//     required String authToken,
//     required bool isAdmin,
//   }) async {
//     await ensureInitialized();

//     final token = await currentToken();
//     if (token == null || token.isEmpty) {
//       // Nothing we can do—FCM not ready yet.
//       return;
//     }

//     final platform = Platform.isAndroid
//         ? 'android'
//         : Platform.isIOS
//             ? 'ios'
//             : 'web';

//     final uri = Uri.parse(
//       backendBaseUrl.endsWith('/')
//           ? '${backendBaseUrl}me/devices/'
//           : '$backendBaseUrl/me/devices/',
//     );

//     await http.post(
//       uri,
//       headers: {
//         'Content-Type': 'application/json',
//         'Authorization': 'Token $authToken',
//       },
//       body: jsonEncode({
//         'token': token,
//         'platform': platform,
//         'is_admin': isAdmin,
//       }),
//     );
//     // We intentionally don’t throw on non-200; login flow shouldn’t be blocked.
//   }

//   /// Keep backend in sync when FCM rotates the token.
//   /// Call this once after login. It cancels/replaces any previous listener.
//   static void subscribeTokenRefresh({
//     required String backendBaseUrl,
//     required Future<String?> Function() getAuthToken,
//     required bool isAdmin,
//   }) {
//     _refreshSub?.cancel();
//     _refreshSub =
//         FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
//       final auth = await getAuthToken();
//       if (auth == null || auth.isEmpty) return;
//       try {
//         await registerDeviceWithBackend(
//           backendBaseUrl: backendBaseUrl,
//           authToken: auth,
//           isAdmin: isAdmin,
//         );
//       } catch (_) {
//         // Silently ignore; we’ll try again on next refresh.
//       }
//     });
//   }

//   /// Optional: call on logout.
//   static Future<void> cancelTokenRefresh() async {
//     await _refreshSub?.cancel();
//     _refreshSub = null;
//   }
// }

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:http/http.dart' as http;

import '../firebase_options.dart'; // generated by flutterfire configure

class PushService {
  PushService._();

  static bool _firebaseReady = false;
  static StreamSubscription<String>? _refreshSub;

  /// Be gentle: safe to call multiple times.
  static Future<void> ensureInitialized() async {
    if (!_firebaseReady) {
      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }
      await FirebaseMessaging.instance.setAutoInitEnabled(true);
      _firebaseReady = true;
    }
  }

  /// Android 13+ needs runtime permission; iOS always does.
  static Future<NotificationSettings> ensurePermissions() async {
    await ensureInitialized();
    final settings = await FirebaseMessaging.instance.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );
    return settings;
  }

  static Future<String?> currentToken() async {
    await ensureInitialized();
    return FirebaseMessaging.instance.getToken();
  }

  static Future<void> registerDeviceWithBackend({
    required String backendBaseUrl, // e.g. https://host/api
    required String authToken,
    required bool isAdmin,
  }) async {
    await ensureInitialized();

    final token = await currentToken();
    if (token == null || token.isEmpty) return;

    final platform = Platform.isAndroid
        ? 'android'
        : Platform.isIOS
            ? 'ios'
            : 'web';

    final base =
        backendBaseUrl.endsWith('/') ? backendBaseUrl : '$backendBaseUrl/';
    final uri = Uri.parse('${base}me/devices/');

    try {
      await http.post(
        uri,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Token $authToken',
        },
        body: jsonEncode({
          'token': token,
          'platform': platform,
          'is_admin': isAdmin,
        }),
      );
    } catch (_) {
      // ignore; don't block UX on push errors
    }
  }

  /// Keep backend in sync when FCM rotates the token.
  static void subscribeTokenRefresh({
    required String backendBaseUrl,
    required Future<String?> Function() getAuthToken,
    required bool isAdmin,
  }) {
    _refreshSub?.cancel();
    _refreshSub =
        FirebaseMessaging.instance.onTokenRefresh.listen((newToken) async {
      final auth = await getAuthToken();
      if (auth == null || auth.isEmpty) return;
      try {
        await registerDeviceWithBackend(
          backendBaseUrl: backendBaseUrl,
          authToken: auth,
          isAdmin: isAdmin,
        );
      } catch (_) {}
    });
  }

  static Future<void> cancelTokenRefresh() async {
    await _refreshSub?.cancel();
    _refreshSub = null;
  }
}
